---
# tasks file for busybox
- name: docker pythong config
  pip:
   name: docker-py

- name: pull busybox image
  community.docker.docker_image:
   name: "{{ container.default_container_image }}"
   source: pull
  # platform: "{{ https://hub.docker.com/_/busybox }}"

- name: create default contaienr
  community.docker.docker_container:
   name: "{{ container.default_container_name }}{{ item }}"
   image: "{{ container.default_container_image }}"
   command: "{{ container.default_container_command }}"
   state: present
  with_sequence: count="{{ container.container_count }}"
