---
# tasks file for busybox
- hosts: all
  become: true
  vars:
    container_count: 1
    default_container_name: busybox
    default_container_image: busybox
    default_container_image: run

  tasks:
    - name: Pull busybox image
      community.docker.docker_image:
        name: "{{default_container_image}}"
        source: pull
           platform: "https://hub.docker.com/_/busybox"

    - name: Create default containers
      community.docker.docker_container:
        name: "{{default_container_name}}{{item}}"
        image: "{{default_container_image}}"
        command: "{{default_container_command}}"
        state: present
      with_sequence: count={{container_count}}
